name: Financial Data Update

on:
  schedule:
    - cron: '0 13 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # This forces the runner to use Node 24 and should silence the warning
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Extraction Script
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: python scripts/extract_finance.py
